feat: update to use faker 7.x -> 9.x
luisrudge/prisma-generator-fake-data pull request #13
Opened 2023-09-14 02:28 UTC by agustif

2023-09-14 20:01 UTC, luisrudge commented
Thanks @agustif. Can you update the code to put the faker-js package in the dependencies list again? I'll merge it in after that.

2023-09-14 20:01 UTC, luisrudge requested changes

2023-09-14 20:01 UTC, luisrudge commented on package.json
> -    "@faker-js/faker": "^7.6.0",
leave it as a dependency

2023-09-15 22:22 UTC, agustif commented on package.json
> -    "@faker-js/faker": "^7.6.0",
Sure thing luis, done now

2023-09-26 16:20 UTC, luisrudge commented
Sorry, I forgot about this :( Seems like the tests are failing because of the new methods.

2023-09-27 01:04 UTC, agustif commented
they are snapshot tests no? probably only need to update the snapshot?

2023-09-27 03:40 UTC, merged

2023-09-27 03:42 UTC, luisrudge commented
@agustif thanks for the help and patience. Released in 0.11.0

2023-09-27 06:04 UTC, agustif commented
> @agustif thanks for the help and patience. Released in 0.11.0

Thank you likewise for your patience with this, should have updated the snapshots tests myself, Github clunky UI not running the tests until you authorize didn't help there but I didn't think to do so locally myself.

Happy that the upgrade got into the latest release!

I had some ideas around doing some kinda based of similarity detection for prisma's model's field names vs faker's available apis, so maybe with just that we would be able to provide better infrence of what fake data to put in each field.

2023-09-27 21:31 UTC, luisrudge commented
@agustif I'd love to see what that looks like!